### ISSUE TITLE
sudo phoronix-test-suite benchmark <GRAPHICAL TEST> fails

### ISSUE THREAD

**Issue by Xeboc** [phoronix-test-suite/phoronix-test-suite#194]
On Ubuntu 17.04, running a graphical benchmark with `sudo` will fail.  I tested on both Intel and NVIDIA machines.  I tested with `unigine-tropics`, `unigine-heaven`, and `openareana`.  This is with a fresh install of 17.04 and current updates.  This is with both `sudo phoronix-test-suite benchmark unigine-tropics` and using Phoromatic with `sudo systemctl start phoromatic-client` and sending a benchmark to the system.

Running all of these benchmarks in user spaces works as expected.  As I'm setting up a Phoromatic client/server setup with `phoromatic-client` being enabled with `systemctl`, I'd like to get the tests to run as root.

The output from running the command above:
```
Unigine Tropics 1.3:
    pts/unigine-tropics-1.6.3 [Resolution: 800 x 600 - Mode: Fullscreen]
    Test 1 of 1
    Estimated Trial Run Count:    3
    Estimated Time To Completion: 11 Minutes [11:26 MDT]
        Started Run 1 @ 11:16:01
        The test run did not produce a result.
        Started Run 2 @ 11:16:02
        The test run did not produce a result.
        Started Run 3 @ 11:16:03
        The test run did not produce a result.
        E: Unigine fatal error
```
And the root user debug-run log:
```
cat /var/lib/phoronix-test-suite/installed-tests/pts/unigine-tropics-1.6.3/unigine-tropics-1.6.3-1502817824-1.log
No protocol specified
Engine::init(): clear video settings for "Unknown GPU"
No protocol specified

Unigine fatal error
Engine::init(): clear video settings for "Unknown GPU"
AppWindow::AppWindow(): can't open display
Loading "/var/lib/phoronix-test-suite/installed-tests/pts/unigine-tropics-1.6.3/tropics/bin/../data/unigine.cfg"...
Loading "libGL.so.1"...
Shutdown
```
And the normal user debug-run:
```
cat /home/james/.phoronix-test-suite/installed-tests/pts/unigine-tropics-1.6.3/unigine-tropics-1.6.3-1502818006-1.log
ATTENTION: default value of option vblank_mode overridden by environment.
Engine::init(): clear video settings for "Mesa DRI Intel(R) Haswell Desktop x86/MMX/SSE2 3.0 Mesa 17.0.7"
ATTENTION: default value of option vblank_mode overridden by environment.
GLRender::GLRender(): Unknown GPU
RenderPostProcess::set_post_textures(): can't find "color_0" texture in "post_blur_radial" material
Loading "/home/james/.phoronix-test-suite/installed-tests/pts/unigine-tropics-1.6.3/tropics/bin/../data/unigine.cfg"...
Loading "libGL.so.1"...
Set 800x600 fullscreen video mode
Set 1.00 gamma value
Unigine engine http://unigine.com/
Binary: Linux 32bit GCC 4.3.2 Release May 20 2010
App path:  /home/james/.phoronix-test-suite/installed-tests/pts/unigine-tropics-1.6.3/tropics/bin/
Data path: /home/james/.phoronix-test-suite/installed-tests/pts/unigine-tropics-1.6.3/tropics/data/
Save path: /home/james/.phoronix-test-suite/installed-tests/pts/unigine-tropics-1.6.3//.Unigine Tropics/

---- System ----
System: Linux 4.10.0-32-generic x86_64
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz 3600MHz MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 HTT
GPU: Mesa DRI Intel(R) Haswell Desktop x86/MMX/SSE2 3.0 Mesa 17.0.7
System memory: 15917 Mb
Video memory:  256 Mb

---- MathLib ----
Set SSE3 simd processor

---- Sound ----
NULL

---- Render ----
OpenGL vendor:   Intel Open Source Technology Center
OpenGL renderer: Mesa DRI Intel(R) Haswell Desktop x86/MMX/SSE2
OpenGL version:  3.0 Mesa 17.0.7
<-- Truncated -->
Shading language:      1.30
Maximum texture size:  16384
Maximum texture units: 192
Maximum draw buffers:  8

---- Physics ----
Physics: Multi-threaded

---- Interpreter ----
Version: 2.31

Loading "tropics/unigine.cpp" 53ms
Loading "demos/tropics/locale/unigine.en" dictionary
Loading "core/materials/unigine_post.mat" 12 materials 12 shaders 0ms
<-- Truncated -->
Loading "core/materials/unigine_decals.mat" 1 material 69 shaders 3ms
Loading "core/properties/unigine.prop" 2 properties 0ms
Unigine~# world_load tropics
Loading "tropics.cpp" 131ms
Loading "demos/tropics/tropics.mat" 40 materials 443ms
Loading "tropics.world" 6986ms
Unigine~# render_hdr 1 && render_srgb 0 && render_restart
Release
Phoronix running
Unigine~# render_stereo 0 && render_restart
Unigine~# render_dof 1 && render_restart
Unigine~# render_dof 0 && render_restart
Phoronix finished
Time:	201.798
Frames:	8980
FPS:	44.4999
Unigine~# quit
Close "libGL.so.1"
Memory usage: 128b
Allocations:  2
Shutdown
```

If I run the same `sudo` command with the version packaged with Ubuntu 17.04, it succeeds (5.2.1-1ubuntu2).  I also tested with the version 5.8 .deb, which is the oldest version that installs without dependency issues in 17.04, version 6.0, and 7.0, and they have the same issue.

Can you help?

Also, a big thank you from System76.  We love your work, software, and articles.  Much appreciated!

**Comment by michaellarabel** [comment]
Hi James, any chance you'd be able to bisect it?

FYI, phoronix-test-suite can be run locally from the tree without having to install it system-wide, etc. Sogenerally can be bisected pretty quickly. Nothing comes to mind with regards to a change around ~5.8 that would affect sudo. Otherwise I can try bisecting in next few days if you're not able to.

Thanks!

**Comment by Xeboc** [comment]
Found it.  `sudo` works fine on this commit:

e27f2cd4f560c02012a980d3844f03e56c058954

And doesn't on this commit:

3eb475733d6b9554d70da399d8ac354c57d69bc9

It looks like it has something to do with the proc_open and how it's being executed.  Maybe the environment isn't being created in a certain way?  It looks like that code hasn't changed since that commit, and that commit replaced a section that was 7 years old.  Isn't `git` awesome?

**Comment by michaellarabel** [comment]
Thanks for bisecting. Will look into it.

**Comment by Xeboc** [comment]
I reverted the exec code back to the previous commit, and then `sudo` commands did run fine.  However, Phoromatic still won't launch graphical tests remotely.  Would switching the systemctl .service to run as a user be the best way to run all tests with Phoromatic?

**Comment by michaellarabel** [comment]
Apologies for the late reply.  At least as a temporary workaround, if running the service as a user may workaround the issue (or otherwise getting the graphical desktop to run as root, if permitted by the desktop). I hope to investigate the issue further in the next few days.

**Comment by michaellarabel** [comment]
@Xeboc the issue should be fixed in latest Git with https://github.com/phoronix-test-suite/phoronix-test-suite/commit/047ee7be4725abe9c976b2f3fc0571fea692936d that will be in the PTS 7.4 release coming out in next week or two.

The issue was just that XAUTHORITY wasn't getting passed. It's now working fine as sudo with Git on my system. Let me know if the issue persists or have other questions, otherwise feel free to open new ticket if other issues.

**Comment by Xeboc** [comment]
Sweet.  I will give it a test!  Thank you.

**Comment by Xeboc** [comment]
Thank you for the commit.  This definitely solves the problem of running a `sudo` graphical command.  I'm still not able to send a computer a graphical test using phoromatic-client as a systemctl service as-is though.  Any suggestions for getting that going?

**Comment by michaellarabel** [comment]
@Xeboc what if you add DISPLAY=:1 environment variable to the systemd service? That's usually the case I've found when configuring phoromatic clients in different scenarios with X11 apps needing DISPLAY set and that usually not being done by default in systemd for services.

**Comment by Xeboc** [comment]
I had the same thought, but I found that it's already in there.  :)

https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/deploy/phoromatic-systemd/phoromatic-client.service

**Comment by michaellarabel** [comment]
Is your desktop running as root (if the service is running a root)? If so, I've never had a problem that way and is how my LinuxBenchmarking.com/Phoromatic systems run. If your session though is running as some user, you may need to run it instead as root or punt the service off to that user.

**Comment by Xeboc** [comment]
Spot on.  I'll just shift the service over to the user (oem).  Thanks for the input.
