### ISSUE TITLE
pts-7.6.0m2 encode-mp3 installation failed

### ISSUE THREAD

**Issue by FabioLolix** [phoronix-test-suite/phoronix-test-suite#204]
pts/encode-mp3-1.6.0:
        Test Installation 2 of 10
        1 File Needed [1.38 MB / 1 Minute]
        Downloading: lame-3.99.5.tar.gz                                                                                                    [1.38MB]
        Estimated Download Time: 1m ...............................................................................................................
        Installation Size: 5 MB
        Installing Test @ 16:31:16
            The installer exited with a non-zero exit status.
            ERROR: collect2: error: ld returned 1 exit status
            LOG: ~/.phoronix-test-suite/installed-tests/pts/encode-mp3-1.6.0/install-failed.log

[pts-7.6.0m2_encode-mp3-1.6.0_install-failed.log](https://github.com/phoronix-test-suite/phoronix-test-suite/files/1438395/pts-7.6.0m2_encode-mp3-1.6.0_install-failed.log)

**Comment by michaellarabel** [comment]
It appears to be an upstream issue in failing to link against the ncurses library.

/usr/bin/ld: console.o: undefined reference to symbol 'tgetnum'
/usr/lib/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Can you confirm if you have the readline or ncurses libraries present on the system?

**Comment by FabioLolix** [comment]
[fabio@fabio-asus ~]$ locate libtinfo.so
/usr/lib/libtinfo.so
/usr/lib/libtinfo.so.5
/usr/lib/libtinfo.so.6
/usr/lib/libtinfo.so.6.0
[fabio@fabio-asus ~]$ pacman -Qo /usr/lib/libtinfo.so.6
/usr/lib/libtinfo.so.6 è contenuto in ncurses 6.0+20170902-2

**Comment by michaellarabel** [comment]
pts/encode-mp3-1.7.0 is now available that pulls in a newer upstream release, LAME 3.100, so hopefully your build issue is fixed by that otherwise feel free to reopen.

**Comment by FabioLolix** [comment]
Thanks, I will try all the fixes in the next days

**Comment by samcv** [comment]
@michaellarabel this issue is not fixed. I'm using PTS v7.8.0 trying to install pts/encode-mp3-1.7.0

I was able to fix it by doing `LDFLAGS=-ltinfo phoronix-test-suite install encode-mp3`, in which case it installed properly. This posting here is what told me the library that needed to be included: https://sourceforge.net/p/lame/mailman/message/32754132/

**Comment by FabioLolix** [comment]
With PTS 8.0.0m3 installing encode-mp3-1.7.0 works fine
