### ISSUE TITLE
using "phoronix-test-suite benchmark 2005145-PTS-RENOIRGF57" asks for "extra/bash-completion" on archlinux

### ISSUE THREAD

**Issue by rezad1393** [phoronix-test-suite/phoronix-test-suite#448]
using "phoronix-test-suite benchmark 2005145-PTS-RENOIRGF57" asks for "extra/bash-completion" on archlinux even though it is installed.
this command asks for root password even though that package is installed and suite doesnt actually install it again just complains about it at start and asks for root password.

suite version: phoronix-test-suite 9.8.0
OS archlinux.

**Comment by michaellarabel** [comment]
Hmmm, do you have Google Chrome installed on your system? I am thinking that may be the cause of it. That test profile contains the 'selenium' test profile for web browser benchmarks that has possible dependencies on Chrome and Firefox. I've seen similar behavior before of some package managers pulling in obscure hits sometimes when trying to find a package match for Chrome.

**Comment by rezad1393** [comment]
I have chromium installed
but removing that doesn't fix this either.

**Comment by michaellarabel** [comment]
This should be fixed in PTS Git. Thanks and sorry for the delay.

**Comment by rezad1393** [comment]
this issue is still present in 10.2.0-1 version in arhclinux.
is this actually fixed?

**Comment by michaellarabel** [comment]
Yes it should be by https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/external-test-dependencies/dependency-handlers/arch_dependency_handler.php#L65

If you have basic debug experience to try confirming if that check is having an issue would be great otherwise I will reconfirm next time I am on an Arch system in a few days.

**Comment by rezad1393** [comment]
I still get this error:
`phoronix-test-suite benchmark 2005145-PTS-RENOIRGF57

NOTICE: The following PHP extensions are OPTIONAL but recommended:

GD        The GD library is recommended for improved graph rendering.
Bzip2     The bzcompress/bzip2 support can be used for greater file compression.
SQLite3   SQLite3 is required when running a Phoromatic server.
Sockets   Sockets is needed when running the Phoromatic Server.



Updated OpenBenchmarking.org Repository Index
pts: 434 Distinct Tests, 1683 Test Versions, 50 Suites
Changes Since 7 January To 10 January
Updated Test Available:  pts/dav1d    v1.7.1 
New Test Available:      pts/openfoam v1.0.1 
Updated OpenBenchmarking.org Repository Index
system: 36 Distinct Tests, 99 Test Versions
Updated OpenBenchmarking.org Repository Index
git: 8 Distinct Tests, 9 Test Versions
    Evaluating External Test Dependencies ......................................................................................................
    Evaluating System Dependencies .............................................................................................................

The following dependencies are needed and will be installed: 

- extra/bash-completion

This process may take several minutes.
Please enter your root password below:
Password: 
`

```
phoronix-test-suite version
Phoronix Test Suite v10.2.0 (Harstad)
```

**Comment by rezad1393** [comment]
> Yes it should be by https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/external-test-dependencies/dependency-handlers/arch_dependency_handler.php#L65
> 
> If you have basic debug experience to try confirming if that check is having an issue would be great otherwise I will reconfirm next time I am on an Arch system in a few days.

any update?
I still have this issue.

**Comment by michaellarabel** [comment]
The latest Git code should have a more universal check for ignoring that package, if you are able to try the latest Git.

**Comment by rezad1393** [comment]
I can wait for the stable release if that's ok.
thank you for the answer.

**Comment by rezad1393** [comment]
it seem to be fixed in latest release.
now I just a warning for xmlrpc that was removed with php7 -> php8.
thank you for the fix.
